package com.manticore.i18n;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.*;

/** UTF-8, sorted, manually escaped .properties writer/reader. */
final class BundleIO {

    private BundleIO() {}

    static void load(Path path, Map<String, String> into) throws IOException {
        for (String line : Files.readAllLines(path, StandardCharsets.UTF_8)) {
            String trimmed = line.stripLeading();
            if (trimmed.isEmpty() || trimmed.startsWith("#") || trimmed.startsWith("!")) continue;
            int eq = findSeparator(line);
            if (eq < 0) continue;
            String key = unescape(line.substring(0, eq).trim());
            String value = unescape(line.substring(eq + 1).stripLeading());
            into.put(key, value);
        }
    }

    static void write(Path path, Map<String, String> bundle) throws IOException {
        Files.createDirectories(path.getParent());
        try (Writer w = Files.newBufferedWriter(path, StandardCharsets.UTF_8)) {
            w.write("# Generated by i18n-extractor\n");
            w.write("# " + LocalDateTime.now() + "\n");
            w.write("# " + bundle.size() + " entries\n\n");

            List<String> keys = new ArrayList<>(bundle.keySet());
            Collections.sort(keys);
            String currentPrefix = null;
            for (String key : keys) {
                String prefix = key.contains(".") ? key.substring(0, key.indexOf('.')) : "";
                if (currentPrefix != null && !currentPrefix.equals(prefix)) {
                    w.write("\n");
                }
                currentPrefix = prefix;
                w.write(escapeKey(key));
                w.write("=");
                w.write(escapeValue(bundle.get(key)));
                w.write("\n");
            }
        }
    }

    private static int findSeparator(String line) {
        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);
            if (c == '\\') { i++; continue; }
            if (c == '=' || c == ':') return i;
        }
        return -1;
    }

    private static String escapeKey(String s) {
        StringBuilder out = new StringBuilder(s.length() + 4);
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case ' ', ':', '=', '#', '!' -> { out.append('\\'); out.append(c); }
                case '\\' -> out.append("\\\\");
                default   -> out.append(c);
            }
        }
        return out.toString();
    }

    private static String escapeValue(String s) {
        StringBuilder out = new StringBuilder(s.length() + 4);
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default   -> out.append(c);
            }
        }
        return out.toString();
    }

    private static String unescape(String s) {
        StringBuilder out = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\' && i + 1 < s.length()) {
                char n = s.charAt(++i);
                switch (n) {
                    case 'n' -> out.append('\n');
                    case 'r' -> out.append('\r');
                    case 't' -> out.append('\t');
                    case 'u' -> {
                        if (i + 4 < s.length()) {
                            out.append((char) Integer.parseInt(s.substring(i + 1, i + 5), 16));
                            i += 4;
                        }
                    }
                    default -> out.append(n);
                }
            } else {
                out.append(c);
            }
        }
        return out.toString();
    }
}
